### PR TITLE
127 update put task to propagate progress upward

### PR DESCRIPTION
**Pull request by emaness-utk**
also simplified code for propagating completion downwards 
also made progress and weight non-nullable w/ default values and range checking

### CODE REVIEW

**Comment by emaness-utk** [comment]
is currently broke, don't approve yet

**Comment by emaness-utk** [comment]
ok it works now im pretty sure

**Review by andlrutt — CHANGES_REQUESTED** [review]
Looks FANTASTIC! Works exactly as expected, and the setters are a nice touch! Just make sure to update the project progress, and run an audit when creating or deleting a task, and this will be good to go!

**Review by andlrutt — APPROVED** [review]
Nice!

**Pull request merged**
